import { MessageCircle, Star } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

export function RatingsAdminPanel({ branchId }: { branchId?: number }) {
  const query = trpc.ratings.owner.list.useQuery(branchId ? { branchId } : undefined, { retry: false });
  const data = query.data;
  return <Card className="mb-6 border border-white/80 bg-white/92 p-5 shadow-lg shadow-sky-900/5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-sky-600">آراء حقيقية فقط</p><h2 className="mt-1 text-xl font-black text-slate-950">تقييمات العملاء</h2></div><div className="flex gap-2"><Badge variant="secondary">{data?.count ?? 0} تقييم</Badge><Badge className="bg-amber-500 text-white"><Star className="ml-1 h-3.5 w-3.5 fill-white" />{(data?.averageStars ?? 0).toLocaleString("ar-SA", { maximumFractionDigits: 1 })}</Badge></div></div>{query.isLoading ? <p className="mt-5 text-sm text-slate-500">جاري تحميل التقييمات...</p> : !data?.ratings.length ? <p className="mt-5 rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">ما وصل أي تقييم حتى الآن.</p> : <div className="mt-5 grid gap-3 lg:grid-cols-2">{data.ratings.map(rating => <article key={rating.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-sky-700">فاتورة #{rating.barcode} · {rating.branchName}</p><h3 className="mt-1 font-black text-slate-900">{rating.customerName || "عميل"} · {rating.deviceInfo}</h3></div><div className="flex gap-0.5">{Array.from({ length: 5 }, (_, index) => <Star key={index} className={`h-4 w-4 ${index < rating.stars ? "fill-amber-400 text-amber-400" : "text-slate-300"}`} />)}</div></div>{rating.feedback && <p className="mt-3 text-sm leading-6 text-slate-600">{rating.feedback}</p>}{rating.contactRequestedAt && <p className="mt-3 flex items-center gap-2 text-xs font-bold text-orange-700"><MessageCircle className="h-4 w-4" />طلب تواصل عبر واتساب</p>}<time className="mt-3 block text-[11px] text-slate-400">{new Date(rating.createdAt).toLocaleString("ar-SA", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Riyadh" })}</time></article>)}</div>}</Card>;
}
